Dulce-Work-Schedule/2018.1-Dulce_App

- docs/sprints/sprint_0.md
- docs/sprints/sprint_1.md
- docs/sprints/sprint_10.md
- docs/sprints/sprint_2.md
- docs/sprints/sprint_3.md
- docs/sprints/sprint_4.md
- docs/sprints/sprint_5.md
- docs/sprints/sprint_6.md
- docs/sprints/sprint_7.md
- docs/sprints/sprint_8.md
- docs/sprints/sprint_9.md
Neste pull request foi feito o template de documentação de sprints.
Signed-off-by: gag2502 <gabrielaalvesdagama@gmail.com>
Signed-off-by: egewarth <egewarth@gmail.com>
> Adicionando template de documentação de sprints

- docs/sprints/sprint_0.md
> WIP: #24 documentar sprint 0

- docs/equipe.md
Alteração do email no arquivo equipe.md
> Alteração do email

- CONTRIBUTING.md
Signed-off-by: Eliseu Egewarth <eliseuegewarth@gmail.com>
Signed-off-by: João Henrique Egewarth <egewarth@gmail.com>
Hotfix do guia de contribuição
> HOTFIX #5 Modificando descrição de merge pra development

- docs/equipe.md
> Fix #43 Atualizando informacoes pessoais

- README.md
Adicionando dados sobre o AGR-APP;
Por que usar o AGR-APP;
Como contribuir;
Desenvolvedores e
Apoiadores.
> Fix #10 Criando README

- docs/tap.md
- Termo de Abertura do Projeto
> Fix #28_termo_de_abertura

- docs/lexico.md
Signed-off-by: Guilherme Deusdará <guibanci@gmail.com>
Signed-off-by: Vitor Leal <vitinho2201@gmail.com>
Signed-off-by: Felipe Campos <fepascampos@gmail.com>
neste pull requeste foi feito o documento do lexico do projeto
> Fix #56 Finalizando o Lexico

- docs/riscos.md
nesse pr foi finalizado o documento de riscos.
> 76 documento riscos

- docs/roadmap.md
Signed-off-by: Isaque alves <isaquealvesdl@gmail.com>
Signed-off-by: João Henrique Egewarth <egewarth@gmail.com>
Signed-off-by: Gabriela Alves da Gama <gabrielaalvesdagama@gmail.com>
Signed-off-by: Eliseu Egewarth <eliseuegewarth@gmail.com>
Co-authored-by: Isaque alves <isaquealvesdl@gmail.com>
Co-authored-by: João Henrique Egewarth <egewarth@gmail.com>
Co-authored-by: Gabriela Alves da Gama <gabrielaalvesdagama@gmail.com>
Co-authored-by: Eliseu Egewarth <eliseuegewarth@gmail.com>
> Fix #91 Adicionando roadmap por papeis

- docs/styleguide.md
Adição do _Style Guide_ do projeto.
> Fix #111 styleguide

- README.md
- Adicionando status badges no README.md:
- Travis CI
- Licença MIT 
- Correção de links (pois o nome do projeto foi alterado)
> HOTFIX #120

- README.md
> HOTFIX #81 Update readme

- __tests__/EditScreen.test.js
- __tests__/ProfileManagerScreen.test.js
- package-lock.json
- package.json
- src/Components/SmallButton.js
- src/Navigators/MainNavigator.js
- src/Screens/LoginScreen.js
- src/Screens/ProfileManagerScreen.js
nesse PR esta sendo feito :
* perfil do gestor
* Issue #69
> WIP:#69 visualiza gestor new

- App.js
- Environment.js
- __tests__/LoginScreen.test.js
- __tests__/__snapshots__/App.js.snap
- __tests__/__snapshots__/LoginScreen.test.js.snap
- __tests__/__snapshots__/NewManager.test.js.snap
- __tests__/__snapshots__/ProfileManagerScreen.test.js.snap
- package-lock.json
- package.json
- src/Components/AGRInput.js
- src/Components/UserItem.js
- src/Navigators/MainNavigator.js
- src/Screens/InitialScreen.js
- src/Screens/LoginScreen.js
> Fix #114_Criar_sessão_de_login

- docs/especificacao/index.html
Signed-off-by: Gabriela Alves da Gama <gabrielaalvesdagama@gmail.com>
Signed-off-by: Isaque alves <isaquealvesdl@gmail.com>
Signed-off-by: João Egewarth <egewarth@gmail.com>
> Fix #133 Adicionando roadmap ao github pages

- docs/especificacao/index.html
Mind map de interação do usuário.
Mapeamento de todas as interações possiveis dos 4 tipos de usuários.
> Fix #174 Criando mind map de interação

- README.md
- Correção de link do test coverage
> HOTFIX #81

- docs/especificacao/index.html
Nesse pull request foi confeccionado o backlog da sprint e o mapa de requisitos.
> 172 backlog produto

- src/Navigators/MainNavigator.js
- src/Screens/EditScreen.js
- src/Screens/InitialScreen.js
- src/Screens/LoginScreen.js
- src/Screens/NewManager.js
@egewarth @eliseuegewarth @gag2502 @alvesisaque gente, eu tive q fazer umas alterações que estavam quebrando a master ou estavam mal elaboradas, são elas
* correção dos inputs da pagina de login
* coloquei o redux para receber os dados do usuario na hora de logar para tê-los na pagina de editar
* mudei alguns placeholders de uns inputs q estavam em ingles
* nomes de variaveis que estavam em portugues
> HOTFIX bugs refatoracao

- docs/abertura/index.html
> Fix #205 Modificando EAP

- src/Screens/EditScreen.js
- src/Screens/EmployeeProfileScreen.js
- src/Screens/ListScreen.js
- src/Screens/LoginScreen.js
- src/Screens/NewManager.js
- src/Screens/ProfileManagerScreen.js
- src/Screens/ProfileScreen.js
Alterações para adequar o APP a nova API.
Issue #198
Adequar FrontEnd à arquitetura do sistema
> Fix#198 Adequar FrontEnd à arquitetura do sistema

- android/app/src/main/res/values/strings.xml
- package.json
- Pequeno ajuste do nome do aplicativo
> HOTFIX #162 Modificando nome do app de 'dulce' para 'Dulce'

- __tests__/Components/ScaleIcon.test.js
- __tests__/Components/SmallButton.test.js
- __tests__/EditScreen.test.js
- __tests__/InitialScreen.test.js
- __tests__/LoginScreen.test.js
- __tests__/NewManager.test.js
- __tests__/__snapshots__/EditScreen.test.js.snap
- __tests__/__snapshots__/InitialScreen.test.js.snap
- src/Screens/EditScreen.js
- src/Screens/InitialScreen.js
- src/Screens/NewManager.js
- src/Screens/ProfileScreen.js
nesse issue foi feito:
* issue #192 
* adequar cobertura de testes ao contexto da disciplina
> WIP:#192 adequar cobertura de testes

- src/Screens/EditScreen.js
- src/Screens/ListScreen.js
- src/Screens/LoginScreen.js
- src/Screens/NewManager.js
- src/Screens/ProfileManagerScreen.js
- src/Screens/ProfileScreen.js
> FIX #232 Mudando para o link da API

- __tests__/EditScreen.test.js
- __tests__/NewManager.test.js
nessa issue foi feito:
* issue #192
> #192 incrementando cobertura de testes

- src/Screens/EditScreen.js
- src/Screens/EmployeeProfileScreen.js
> FIX #236 Adicionando o Scroll e corrigindo um link da API em tela inutil

- App.js
- __tests__/HospitalsScreen.test.js
- __tests__/SectorsScreen.test.js
- __tests__/__snapshots__/App.js.snap
- __tests__/__snapshots__/EditScreen.test.js.snap
- __tests__/__snapshots__/HospitalsScreen.test.js.snap
- __tests__/__snapshots__/SectorsScreen.test.js.snap
- src/Components/routes.js
- src/Screens/HospitalsScreen.js
- src/Screens/SectorsScreen.js
Nesta issue foi feita a tela de listagem de hospitais, mas sem conexão com api
> Fix #189 visualizar hospitais

- __tests__/HospitalsScreen.test.js
- __tests__/__snapshots__/App.js.snap
- __tests__/__snapshots__/HospitalsScreen.test.js.snap
- __tests__/__snapshots__/SectorsScreen.test.js.snap
- src/Components/routes.js
- src/Navigators/HospitalsNavigation.js
- src/Navigators/SectorsNavigation.js
- src/Routes/Hospitals.js
- src/Routes/Sectors.js
- src/Screens/HospitalsScreen.js
- src/Screens/SectorsScreen.js
nesta issue foi feita a tela de visualizar setores sem a conexão com a api.
> Fix #190 visualizar setores

- .travis.yml
- package.json
- utils/write_coveralls_config.sh
> Fix #225 Jest Timeout

- .travis.yml
- package.json
Correções no package.json e travis.
> FIX #336 corrigir travis

- docs/signatures.txt
Signed-off-by: Felipe Campos <fepascampos@gmail.com>
Nesse PR foi feita a criação do documento de assinaturas, nada muito complexo, creio que não sejam necessárias grandes revisões.
> FIX #340 adicionando documento de assinaturas

- App.js
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- package.json
- src/Screens/EditScreen.js
- src/Screens/HospitalsScreen.js
- src/Screens/ProfileManagerScreen.js
- src/Screens/ProfileScreen.js
- src/Screens/SectorsScreen.js
- src/Screens/WeekSchedule.js
Neste pull request foi feita refatoração da tela de visualizar horarios com a nova opçao de solicitar troca de horário com outro funcionário
> Fix #331 trocar escala

- App.js
- package-lock.json
- package.json
- src/Components/routes.js
- src/Screens/EditScreen.js
- src/Screens/EmployeeProfileScreen.js
- src/Screens/ListScreen.js
- src/Screens/LoginScreen.js
- src/Screens/NewManager.js
- src/Screens/ProfileManagerScreen.js
- src/Screens/ProfileScreen.js
> Fix #319 Aplicar navegabilidade de telas

- src/Screens/WeekSchedule.js
* conexão do visual com o back end em relação as escalas da semana
> FIX #303 escala semana funcionalidade

- .travis.yml
- Correção de bugs da Issue #216
> HOTFIX: #216 Arrumando configuração de deploy do travis

- __tests__/Components/ListElements.test.js
- __tests__/Components/ScheduleItem.test.js
- __tests__/Components/ScreenHeader.test.js
- __tests__/Components/ValidateButton.test.js
- __tests__/Components/__snapshots__/ListElements.test.js.snap
- __tests__/Components/__snapshots__/ScheduleItem.test.js.snap
- __tests__/Components/__snapshots__/ScreenHeader.test.js.snap
- __tests__/Components/__snapshots__/ValidateButton.test.js.snap
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/NewManager.test.js
- __tests__/Screens/__snapshots__/EditScreen.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Screens/EditScreen.js
- src/Screens/NewManager.js
Neste PR, foi feito( pela terceira vez ¯\_(ツ)_/¯ ) :
- Ajustes no Code Climate (issue #353)
> HOTFIX: 353_maintainability_A

- App.js
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/WeekSchedule.test.js
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- android/app/src/main/res/values/styles.xml
- package.json
- src/Screens/WeekSchedule.js
Nesse Pull Request foi feito:
#330
> FIX #330 editar horario

- .travis.yml
- utils/run_build_in_branch.sh
- utils/run_test_tag_version.sh
- HOTFIX Issue #216
Correção de bugs
> HOTFIX #216 Adicionando clausula para evitar deploy em PRs

- __tests__/Components/ListElements.test.js
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/WeekSchedule.test.js
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Screens/WeekSchedule.js
- Issue #392 (Testes na tela WeekSchedule)
> FIX #392_testes_week_schedule

- App.js
- __tests__/Components/SignUpButton.test.js
- __tests__/Components/__snapshots__/AGRInput.test.js.snap
- __tests__/Components/__snapshots__/GoogleButton.test.js.snap
- __tests__/Components/__snapshots__/SignUpButton.test.js.snap
- __tests__/Routes/__snapshots__/NewManager.test.js.snap
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/NewUser.test.js
- __tests__/Screens/__snapshots__/EditScreen.test.js.snap
- __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
- __tests__/Screens/__snapshots__/NewManager.test.js.snap
- __tests__/Screens/__snapshots__/NewUser.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- package-lock.json
- package.json
- src/Components/SignUpButton.js
- src/Navigators/NewUserNavigator.js
- src/Screens/NewUser.js
Nesse Pr foi feito:
* issue #389 (Tela de cadastro de Usuário)
> #FIX 389_cadastro_user

- src/Navigators/ListProfileNavigator.js
- src/Screens/ListProfile.js
Nesse Pull Request foi feito:
#375
> FIX 375 lista perfil

- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/ListProfile.test.js
- __tests__/Screens/__snapshots__/ListProfile.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Screens/ListProfile.js
> FIX #376 botão listar perfis 

- src/Components/routes.js
- src/Navigators/NewProfileNavigator.js
- src/Routes/NewProfile.js
- src/Screens/NewProfile.js
- src/Screens/NewUser.js
Nesse Pull Request foi feito:
#380
> FIX #380 cadastro perfil

- src/Components/routes.js
- src/Navigators/ListProfileNavigator.js
- src/Routes/Profiles.js
Issue #412 :
- Foi adicionado ao side menu a tela de visualizar perfis
> Fix #412 Aplicando navegação para ListProfile

- docs/viabilidade-tecnica/index.html
- docs/viabilidade-tecnica/metodologia.html
- docs/viabilidade-tecnica/metricas_indicadores.html
- docs/viabilidade-tecnica/ritos_adotados.html
- docs/viabilidade-tecnica/sprint/sprint_6-15.html
> [ci skip] Fix #431 doc metodologia

- __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/LoginScreen.test.js
- __tests__/Screens/__snapshots__/LoginScreen.test.js.snap
- __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Navigators/LoginNavigator.js
- src/Screens/LoginScreen.js
Issue #410 
- O botão de cadastrar da tela de login agora redireciona para a tela de novo usuário
> FIX #410 Aplicando navegabilidade para tela de cadastro

- src/Components/routes.js
- src/Navigators/AbsencesNavigator.js
- src/Routes/Absences.js
> Fix #416 navegabilidade abono

- src/Screens/ProfileManagerScreen.js
Conteúdo do Pull Request
- Ligação ProfileManagerScreen com a api que esta em produção.
- Issue #419
> FIX #419 Ligando tela com a api em produçao

- App.js
- ios/dulce.xcodeproj/project.pbxproj
- src/Components/GoogleButton.js
- src/Screens/LoginScreen.js
> Fix #456 alert login

- src/Components/AGRInput.js
> FIX #458 Arrumando styles do login

- src/Components/Absences.js
- src/Components/SignUpButton.js
- src/Navigators/LoginNavigator.js
- src/Screens/EditScreen.js
> Fix #462 text botoes

- src/Screens/NotificationScreen.js
> FIX #464 Arrumando botão aceitar

- __tests__/Screens/AbsencesScreen.test.js
- __tests__/Screens/ListProfile.test.js
- src/Components/Absences.js
- src/Screens/AbsencesScreen.js
- src/Screens/NotificationScreen.js
Nesse Pull Request foi feito:
#469
> FIX #469 alert telas

- src/Screens/ListProfile.js
> FIX #472 melhorar lista perfil

- __mocks__/api_data.json
- __mocks__/axios.js
- __tests__/Components/__snapshots__/Absences.test.js.snap
- __tests__/Components/__snapshots__/DateRangePicker.test.js.snap
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/ListProfile.test.js
- __tests__/Screens/LoginScreen.test.js
- __tests__/Screens/NewUser.test.js
- __tests__/Screens/__snapshots__/AbsencesScreen.test.js.snap
- __tests__/Screens/__snapshots__/ListProfile.test.js.snap
- __tests__/Screens/__snapshots__/NewUser.test.js.snap
- __tests__/Screens/__snapshots__/VacationScreen.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Components/SideMenu.js
- src/Screens/ListProfile.js
- src/Screens/LoginScreen.js
- src/Screens/NewUser.js
neste pull request foi feito:
issue #466 Colocar nome e email do usuário no side Menu e conectar login e novo usuário com a api
> Fix #466 conectar login e side menu

- __tests__/Reducers/ReducerCurrentUser.test.js
- __tests__/Routes/__snapshots__/Schedule.test.js.snap
- __tests__/Screens/__snapshots__/WeekSchedule.test.js.snap
- src/Components/SideMenu.js
- src/Reducers/currentUser.js
- src/Screens/InitialScreen.js
- src/Screens/LoginScreen.js
- src/Screens/ProfileManagerScreen.js
Nesse PR está sendo feito:
- issue #346
> FIX #346 redux logout

- __tests__/Components/ScreenHeader.test.js
- __tests__/Screens/EditScreen.test.js
- __tests__/Screens/NewUser.test.js
- src/Components/ScreenHeader.js
- src/Screens/EditScreen.js
- src/Screens/NewProfile.js
- src/Screens/NewUser.js
- issue #473 
Foi adicionado o botão de voltar nas telas NewUser, NewProfile e EditScreen
> Fix #473 Adicionando botão de voltar das páginas secundárias

- src/Components/AGRButton.js
> Fix #470 Arrumando o tamanho da ScrollView.
